[package]
name = "proofs"
version = "0.1.0"
authors = ["Dylan McKay <me@dylanmckay.io>"]
publish = false

[dependencies]
# hmdee = { git = "https://github.com/dylanmckay/hmdee.git" }
hmdee = { path = "../../hmdee/hmdee" }
